# Generated by Django 5.0.3 on 2024-03-31 11:09

import django.db.models.deletion
import django.utils.timezone
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('---select one---', '---select one---'), ('Accounting', 'Accounting'), ('Bids and Awards Committee', 'Bids and Awards Committee'), ('Budget Office', 'Budget Office'), ('General Services', 'General Services'), ('Municipal Environment & Natural Resources', 'Municipal Environment & Natural Resources'), ('Municipal Treasury', 'Municipal Treasury'), ("Mayor's Office", "Mayor's Office")], default='---select one---', max_length=80, verbose_name='Department: ')),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('ext_name', models.CharField(blank=True, max_length=3, null=True, verbose_name='Extension')),
                ('image', models.ImageField(blank=True, default='defaults/default_user_dp.png', upload_to=user.models.User.dp_directory_path, verbose_name='Photo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.department')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='dept_head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.departmenthead'),
        ),
    ]
